# Generated by Django 5.2.13 on 2026-04-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='doc_image',
        ),
    ]
