# Generated by Django 5.2.13 on 2026-04-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_doctors_doc_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors'),
        ),
    ]
